#.\.venv\Scripts\Activate.ps1
#uvicorn main:app --reload
#Research Tesla earnings
#Find the route from Delhi to Jaipur
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware


# ============================================================================
# AEGIS SERVICES
# ============================================================================

from request_history import (
    get_requests,
    get_dashboard_stats,
    decide_request,
)

from selector import select_api

from policy_builder import generate_policy_suggestions

from policy_store import (
    get_policy_config,
    toggle_guardrail,
    apply_policy_suggestion,
)

from blockchain import (
    get_blockchain_records,
    get_blockchain_record,
    get_blockchain_stats,
    verify_blockchain,
)


# ============================================================================
# x402 PAYMENT SERVICES
# ============================================================================

from x402.payment_models import (
    PaymentRequest,
    PaymentAuthorization,
)

from x402.payment_service import (
    create_payment_request,
    get_payment,
    authorize_payment,
    verify_payment,
    settle_payment,
)


# ============================================================================
# FASTAPI APPLICATION
# ============================================================================

app = FastAPI(
    title="AEGIS Intelligence API"
)


# ============================================================================
# CORS
# ============================================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================================
# GENERAL REQUEST MODELS
# ============================================================================

class PromptRequest(BaseModel):
    message: str


class DecisionRequest(BaseModel):
    decision: str


# ============================================================================
# HOME
# ============================================================================

@app.get("/")
def home():
    return {
        "message": "AEGIS API is running 🚀"
    }


# ============================================================================
# AGENT / TASK EXECUTION
# ============================================================================

@app.post("/execute-task")
def select(request: PromptRequest):
    """
    Submit a task to AEGIS.

    The selector/guardrails layer decides whether the request is:
    - approved
    - human_review
    - blocked

    Automatically approved requests are handled by selector.py.
    Human-approved requests are handled by /requests/{request_id}/decision.
    """
    return select_api(request.message)


# ============================================================================
# REQUEST HISTORY
# ============================================================================

@app.get("/requests")
def requests():
    return get_requests()


# ============================================================================
# APPROVE / REJECT REQUEST
# ============================================================================
#
# IMPORTANT:
# There is ONLY ONE decision route in this file.
#
# When a request is manually approved:
#
#     request
#       ↓
#     approved
#       ↓
#     create payment
#       ↓
#     backend generates transaction_id
#       ↓
#     /transactions can see it
#
# The transaction_id is NOT generated by React.
# ============================================================================

@app.post("/requests/{request_id}/decision")
def make_decision(
    request_id: str,
    body: DecisionRequest,
):
    decision = body.decision.lower().strip()

    if decision not in {"approved", "rejected"}:
        raise HTTPException(
            status_code=400,
            detail="Decision must be 'approved' or 'rejected'.",
        )

    # Update the original request first.
    updated = decide_request(
        request_id,
        decision,
    )

    if updated is None:
        raise HTTPException(
            status_code=404,
            detail="Payment request not found.",
        )

    # ------------------------------------------------------------------------
    # APPROVED
    # ------------------------------------------------------------------------
    #
    # Creating the payment record automatically creates a transaction ID
    # inside x402/payment_service.py.
    #
    # Example:
    #
    # payment_id     = UUID
    # transaction_id = TX-A1B2C3D4
    #
    # No fake transaction ID is generated in the frontend.
    # ------------------------------------------------------------------------

    if decision == "approved":

        try:
            payment = create_payment_request(
                request_id=request_id,
                task=updated.get(
                    "task",
                    "Approved payment request",
                ),
                provider=updated.get(
                    "provider",
                    "Unknown Provider",
                ),
                api=updated.get(
                    "api",
                    "x402 Payment API",
                ),
                amount=float(
                    updated.get(
                        "amount",
                        0,
                    )
                ),
            )

        except Exception as exc:
            print(
                "❌ PAYMENT CREATION FAILED:",
                repr(exc),
            )

            raise HTTPException(
                status_code=500,
                detail=f"Payment creation failed: {str(exc)}",
            )

        print(
            "✅ PAYMENT CREATED:",
            payment.get("payment_id"),
        )

        print(
            "🔗 TRANSACTION CREATED:",
            payment.get("transaction_id"),
        )

        return {
            **updated,

            "payment_created": True,

            "payment_id": payment.get(
                "payment_id"
            ),

            "transaction_id": payment.get(
                "transaction_id"
            ),

            "payment_status": payment.get(
                "status"
            ),

            "payment": payment,
        }

    # ------------------------------------------------------------------------
    # REJECTED
    # ------------------------------------------------------------------------

    return {
        **updated,

        "payment_created": False,

        "payment_id": None,

        "transaction_id": None,

        "payment_status": None,
    }


# ============================================================================
# DASHBOARD
# ============================================================================

@app.get("/dashboard")
def dashboard():
    return get_dashboard_stats()


# ============================================================================
# BLOCKCHAIN
# ============================================================================

@app.get("/blockchain")
def get_blockchain():
    return get_blockchain_records()


@app.get("/blockchain/stats")
def blockchain_stats():
    return get_blockchain_stats()


@app.get("/blockchain/verify")
def verify_chain():
    return verify_blockchain()


@app.get("/blockchain/{block_number}")
def get_block(block_number: int):

    block = get_blockchain_record(
        block_number
    )

    if block is None:
        return {
            "error": "Block not found"
        }

    return block


# ============================================================================
# POLICY MANAGEMENT
# ============================================================================

@app.get("/policy-suggestions")
def policy_suggestions():
    return generate_policy_suggestions()


@app.get("/policies")
def policies():
    return get_policy_config()


@app.post("/policies/apply")
def apply_policy(
    suggestion: dict,
):
    try:
        return apply_policy_suggestion(
            suggestion
        )

    except ValueError as exc:
        return {
            "success": False,
            "message": str(exc),
        }


# ============================================================================
# GUARDRAILS
# ============================================================================

@app.get("/guardrails")
def get_guardrails():

    config = get_policy_config()

    enabled = config[
        "guardrails_enabled"
    ]

    return [

        {
            "id": "provider_allow_list",
            "name": "Provider Allow List",
            "category": "access",
            "description":
                "Controls which providers agents may use.",
            "enabled":
                enabled["provider_allow_list"],
            "threshold":
                f"{len(config['allowed_providers'])} providers allowed",
            "triggeredCount": 0,
        },

        {
            "id": "auto_approval_limit",
            "name": "Autonomous Approval Limit",
            "category": "spending",
            "description":
                "Maximum amount that can be automatically approved.",
            "enabled":
                enabled["auto_approval_limit"],
            "threshold":
                f"${config['auto_approve_limit']:,.0f}",
            "triggeredCount": 0,
        },

        {
            "id": "human_review_limit",
            "name": "Human Review Threshold",
            "category": "compliance",
            "description":
                "Transactions above the autonomous limit require human approval.",
            "enabled":
                enabled["human_review_limit"],
            "threshold":
                f"Up to ${config['human_review_limit']:,.0f}",
            "triggeredCount": 0,
        },

        {
            "id": "daily_budget",
            "name": "Daily Spending Budget",
            "category": "spending",
            "description":
                "Maximum allowed spending per day.",
            "enabled":
                enabled["daily_budget"],
            "threshold":
                f"${config['daily_budget']:,.0f}",
            "triggeredCount": 0,
        },

        {
            "id": "frequency_limit",
            "name": "Request Frequency Limit",
            "category": "behavioral",
            "description":
                "Limits how many requests can be processed within the configured period.",
            "enabled":
                enabled["frequency_limit"],
            "threshold":
                f"{config['frequency_limit']} requests",
            "triggeredCount": 0,
        },

    ]


class GuardrailToggleRequest(BaseModel):
    enabled: bool


@app.post(
    "/guardrails/{guardrail_id}/toggle"
)
def toggle_guardrail_endpoint(
    guardrail_id: str,
    body: GuardrailToggleRequest,
):

    try:

        config = toggle_guardrail(
            guardrail_id,
            body.enabled,
        )

        enabled = config[
            "guardrails_enabled"
        ]

        guardrails_map = {

            "provider_allow_list": {
                "name":
                    "Provider Allow List",
                "category":
                    "access",
                "description":
                    "Controls which providers agents may use.",
                "threshold":
                    f"{len(config['allowed_providers'])} providers allowed",
            },

            "auto_approval_limit": {
                "name":
                    "Autonomous Approval Limit",
                "category":
                    "spending",
                "description":
                    "Maximum amount that can be automatically approved.",
                "threshold":
                    f"${config['auto_approve_limit']:,.0f}",
            },

            "human_review_limit": {
                "name":
                    "Human Review Threshold",
                "category":
                    "compliance",
                "description":
                    "Transactions above the autonomous limit require human approval.",
                "threshold":
                    f"Up to ${config['human_review_limit']:,.0f}",
            },

            "daily_budget": {
                "name":
                    "Daily Spending Budget",
                "category":
                    "spending",
                "description":
                    "Maximum allowed spending per day.",
                "threshold":
                    f"${config['daily_budget']:,.0f}",
            },

            "frequency_limit": {
                "name":
                    "Request Frequency Limit",
                "category":
                    "behavioral",
                "description":
                    "Limits how many requests can be processed within the configured period.",
                "threshold":
                    f"{config['frequency_limit']} requests",
            },

        }

        if guardrail_id not in guardrails_map:
            raise ValueError(
                f"Unknown guardrail: {guardrail_id}"
            )

        item = guardrails_map[
            guardrail_id
        ]

        return {
            "id": guardrail_id,
            **item,
            "enabled":
                enabled[guardrail_id],
            "triggeredCount": 0,
        }

    except ValueError as exc:

        raise HTTPException(
            status_code=400,
            detail=str(exc),
        )


# ============================================================================
# x402 PAYMENT FLOW
# ============================================================================

@app.post("/x402/payment")
def create_x402_payment(
    request: PaymentRequest,
):
    """
    Create an x402-style payment request.

    IMPORTANT:
    transaction_id is intentionally NOT supplied here.

    payment_service.py generates it on the backend.
    """

    try:

        payment = create_payment_request(
            request_id=request.request_id,
            task=request.task,
            provider=request.provider,
            api=request.api,
            amount=request.amount,
        )

    except Exception as exc:

        print(
            "❌ x402 PAYMENT CREATION FAILED:",
            repr(exc),
        )

        raise HTTPException(
            status_code=500,
            detail=f"Payment creation failed: {str(exc)}",
        )

    return {
        "status": 402,
        "message": "Payment Required",
        "payment": payment,
    }


@app.get(
    "/x402/payment/{payment_id}"
)
def get_x402_payment(
    payment_id: str,
):

    payment = get_payment(
        payment_id
    )

    if payment is None:

        raise HTTPException(
            status_code=404,
            detail="Payment not found",
        )

    return payment


@app.post(
    "/x402/payment/{payment_id}/authorize"
)
def authorize_x402_payment(
    payment_id: str,
    body: PaymentAuthorization,
):

    payment = authorize_payment(
        payment_id,
        body.payment_signature,
    )

    if payment is None:

        raise HTTPException(
            status_code=404,
            detail="Payment not found",
        )

    return payment


@app.post(
    "/x402/payment/{payment_id}/verify"
)
def verify_x402_payment(
    payment_id: str,
):

    payment = verify_payment(
        payment_id
    )

    if payment is None:

        raise HTTPException(
            status_code=404,
            detail="Payment not found",
        )

    return payment


@app.post(
    "/x402/payment/{payment_id}/settle"
)
def settle_x402_payment(
    payment_id: str,
):

    payment = settle_payment(
        payment_id
    )

    if payment is None:

        raise HTTPException(
            status_code=404,
            detail="Payment not found",
        )

    return payment


# ============================================================================
# x402 EXECUTION
# ============================================================================

@app.post(
    "/x402/execute/{payment_id}"
)
def execute_x402_payment(
    payment_id: str,
):

    payment = get_payment(
        payment_id
    )

    if payment is None:

        raise HTTPException(
            status_code=404,
            detail="Payment not found",
        )

    if payment["status"] != "settled":

        raise HTTPException(
            status_code=400,
            detail="Payment has not been settled.",
        )

    return {
        "success": True,

        "payment_id":
            payment_id,

        "transaction_hash":
            payment["transaction_hash"],

        "provider":
            payment["provider"],

        "api":
            payment["api"],

        "task":
            payment["task"],

        "message":
            "Payment settled. Service execution authorized.",
    }


# ============================================================================
# PAYMENT REQUEST CREATION
# ============================================================================

class PaymentRequestCreate(BaseModel):
    request_id: str
    task: str
    provider: str
    api: str
    amount: float


@app.post("/payments/request")
def create_payment(
    data: PaymentRequestCreate,
):

    try:

        payment = create_payment_request(
            request_id=data.request_id,
            task=data.task,
            provider=data.provider,
            api=data.api,
            amount=data.amount,
        )

    except Exception as exc:

        print(
            "❌ PAYMENT REQUEST CREATION FAILED:",
            repr(exc),
        )

        raise HTTPException(
            status_code=500,
            detail=f"Payment creation failed: {str(exc)}",
        )

    return {
        "success": True,

        "payment_id":
            payment.get("payment_id"),

        "request_id":
            payment.get("request_id"),

        "transaction_id":
            payment.get("transaction_id"),

        "task":
            payment.get("task"),

        "provider":
            payment.get("provider"),

        "api":
            payment.get("api"),

        "amount":
            payment.get("amount"),

        "currency":
            payment.get(
                "currency",
                "USDC",
            ),

        "network":
            payment.get(
                "network",
                "Base Sepolia",
            ),

        "pay_to":
            payment.get("pay_to"),

        "status":
            payment.get(
                "status",
                "payment_required",
            ),

        "payment_signature":
            payment.get(
                "payment_signature"
            ),

        "transaction_hash":
            payment.get(
                "transaction_hash"
            ),

        "created_at":
            payment.get(
                "created_at"
            ),

        "settled_at":
            payment.get(
                "settled_at"
            ),
    }


# ============================================================================
# TRANSACTIONS
# ============================================================================
#
# Transactions are currently derived from the AEGIS x402 payment store.
#
# This means:
#
#   approved request
#          ↓
#   create_payment_request()
#          ↓
#   payment stored in payments{}
#          ↓
#   GET /transactions
#          ↓
#   frontend
#
# No fake frontend transaction data is required.
# ============================================================================

@app.get("/transactions")
def get_transactions():

    from x402.payment_service import payments

    transactions = []

    for payment in payments.values():

        transactions.append({

            "id":
                payment.get(
                    "transaction_id"
                ),

            "request_id":
                payment.get(
                    "request_id"
                ),

            "payment_id":
                payment.get(
                    "payment_id"
                ),

            "task":
                payment.get(
                    "task"
                ),

            "provider":
                payment.get(
                    "provider"
                ),

            "api":
                payment.get(
                    "api"
                ),

            "amount":
                payment.get(
                    "amount"
                ),

            "currency":
                payment.get(
                    "currency",
                    "USDC",
                ),

            "network":
                payment.get(
                    "network",
                    "Base Sepolia",
                ),

            "pay_to":
                payment.get(
                    "pay_to"
                ),

            "status":
                payment.get(
                    "status",
                    "payment_required",
                ),

            "transaction_hash":
                payment.get(
                    "transaction_hash"
                ),

            "payment_signature":
                payment.get(
                    "payment_signature"
                ),

            "created_at":
                payment.get(
                    "created_at"
                ),

            "settled_at":
                payment.get(
                    "settled_at"
                ),
        })

    return transactions


# ============================================================================
# PAYMENT DETAILS
# ============================================================================

@app.get("/payments/{payment_id}")
def get_payment_details(
    payment_id: str,
):

    payment = get_payment(
        payment_id
    )

    if payment is None:

        raise HTTPException(
            status_code=404,
            detail="Payment not found",
        )

    return {
        "success": True,
        "payment": payment,
    }