import uuid
from datetime import datetime, timezone
from typing import Dict, Optional


# ============================================================================
# PAYMENT CONFIGURATION
# ============================================================================

PAYMENT_NETWORK = "Base Sepolia"
PAYMENT_CURRENCY = "USDC"

# Placeholder until real blockchain settlement is connected.
PAY_TO_ADDRESS = "0x0000000000000000000000000000000000000000"


# ============================================================================
# IN-MEMORY PAYMENT STORE
# ============================================================================

payments: Dict[str, dict] = {}


# ============================================================================
# CREATE PAYMENT REQUEST
# ============================================================================

def create_payment_request(
    request_id: str,
    task: str,
    provider: str,
    api: str,
    amount: float,
):
    """
    Creates an internal AEGIS payment execution record.

    The payment ID and transaction ID are generated by the backend.
    The frontend does not fabricate transaction identifiers.
    """

    payment_id = str(uuid.uuid4())

    transaction_id = (
        f"TX-{uuid.uuid4().hex[:8].upper()}"
    )

    payment = {
        "payment_id": payment_id,

        "request_id": request_id,

        "transaction_id": transaction_id,

        "task": task,

        "provider": provider,

        "api": api,

        "amount": amount,

        "currency": PAYMENT_CURRENCY,

        "network": PAYMENT_NETWORK,

        "pay_to": PAY_TO_ADDRESS,

        "status": "payment_required",

        "payment_signature": None,

        "transaction_hash": None,

        "created_at": datetime.now(
            timezone.utc
        ).isoformat(),

        "settled_at": None,
    }

    payments[payment_id] = payment

    return payment


# ============================================================================
# GET PAYMENT
# ============================================================================

def get_payment(
    payment_id: str,
) -> Optional[dict]:

    return payments.get(payment_id)


# ============================================================================
# AUTHORIZE PAYMENT
# ============================================================================

def authorize_payment(
    payment_id: str,
    payment_signature: str,
):

    payment = payments.get(payment_id)

    if payment is None:
        return None

    payment["payment_signature"] = payment_signature

    payment["status"] = "authorized"

    return payment


# ============================================================================
# VERIFY PAYMENT
# ============================================================================

def verify_payment(
    payment_id: str,
):

    payment = payments.get(payment_id)

    if payment is None:
        return None

    if not payment.get("payment_signature"):

        payment["status"] = "verification_failed"

        return payment

    payment["status"] = "verified"

    return payment


# ============================================================================
# BEGIN SETTLEMENT
# ============================================================================

def settle_payment(
    payment_id: str,
):

    payment = payments.get(payment_id)

    if payment is None:
        return None

    if payment["status"] != "verified":

        return payment

    payment["status"] = "settling"

    return payment


# ============================================================================
# COMPLETE SETTLEMENT
# ============================================================================

def complete_settlement(
    payment_id: str,
    transaction_hash: str,
):

    payment = payments.get(payment_id)

    if payment is None:
        return None

    payment["transaction_hash"] = transaction_hash

    payment["status"] = "settled"

    payment["settled_at"] = datetime.now(
        timezone.utc
    ).isoformat()

    return payment